"""Run handcrafted-baseline FID sweeps (DEIS / DPM-Solver++ / UniPC / iPNDM)
using diff-sampler's diff-solvers-main, with the recommended settings from its
README (which match the paper's Table 5 baselines):

  DPM-Solver++(3M): logsnr schedule, predict_x0, lower_order_final
  UniPC-3:          logsnr schedule, predict_x0, lower_order_final, bh2
  DEIS-tAB3:        time_uniform schedule (rho=2), tab mode
  iPNDM-4:          polynomial schedule (rho=7)

For these multistep solvers NFE = num_steps - 1. Images are generated by
subprocess calls to diff-solvers-main/sample.py (single GPU; its dist.init()
defaults to a 1-process group), FID by our pipeline. Results accumulate in
results/baselines.csv; existing rows are skipped, so the sweep is resumable.

Example (full Table 5 baseline sweep for CIFAR-10):
  uv run python scripts/run_baselines.py --dataset cifar10 --solvers deis,dpmpp,unipc --nfes 4-10

Cross-check: published FIDs in external/diff-sampler/diff-solvers-main/README.md
(e.g. CIFAR-10 iPNDM-4 NFE6 = 7.05) validate the whole pipeline.
"""

import csv
import shutil
import subprocess
import sys
from pathlib import Path

import click
import torch

from dlms.bootstrap import DIFF_SOLVERS_DIR, RESULTS_DIR, SAMPLES_DIR
from dlms.fid_utils import compute_fid
from dlms.generate import parse_int_list

SOLVER_FLAGS = {
    "dpmpp": ["--solver=dpmpp", "--schedule_type=logsnr", "--max_order=3",
              "--predict_x0=True", "--lower_order_final=True"],
    "unipc": ["--solver=unipc", "--schedule_type=logsnr", "--max_order=3",
              "--predict_x0=True", "--lower_order_final=True", "--variant=bh2"],
    "deis":  ["--solver=deis", "--schedule_type=time_uniform", "--schedule_rho=2",
              "--deis_mode=tab", "--max_order=3"],
    "ipndm": ["--solver=ipndm", "--schedule_type=polynomial", "--schedule_rho=7",
              "--max_order=4"],
}


def load_done(csv_path):
    done = set()
    if csv_path.exists():
        with open(csv_path) as f:
            for row in csv.DictReader(f):
                done.add((row["dataset"], row["solver"], int(row["nfe"])))
    return done


@click.command()
@click.option("--dataset", "dataset_name", type=click.Choice(["cifar10", "ffhq", "imagenet64"]), required=True)
@click.option("--solvers", type=str, default="deis,dpmpp,unipc", show_default=True)
@click.option("--nfes", type=str, default="4-10", show_default=True)
@click.option("--seeds", type=str, default="0-49999", show_default=True)
@click.option("--fid-num", type=int, default=50000, show_default=True)
@click.option("--batch", type=int, default=128, show_default=True)
@click.option("--keep-images", is_flag=True, help="Keep generated images after FID.")
@click.option("--csv-path", type=click.Path(), default=None,
              help="Results CSV (default results/baselines.csv).")
def main(dataset_name, solvers, nfes, seeds, fid_num, batch, keep_images, csv_path):
    csv_path = Path(csv_path) if csv_path else RESULTS_DIR / "baselines.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    done = load_done(csv_path)
    solvers = [s.strip() for s in solvers.split(",")]
    nfe_list = parse_int_list(nfes)

    for solver in solvers:
        assert solver in SOLVER_FLAGS, f"unknown solver {solver}"
        for nfe in nfe_list:
            if (dataset_name, solver, nfe) in done:
                print(f"[skip] {dataset_name} {solver} NFE {nfe} (already in {csv_path})")
                continue
            outdir = SAMPLES_DIR / dataset_name / f"{solver}_nfe{nfe}"
            cmd = [sys.executable, "sample.py",
                   f"--dataset_name={dataset_name}", f"--batch={batch}",
                   f"--seeds={seeds}", f"--num_steps={nfe + 1}", "--afs=False",
                   f"--outdir={outdir}", "--subdirs"] + SOLVER_FLAGS[solver]
            print(f"[run ] {dataset_name} {solver} NFE {nfe}: {' '.join(cmd[1:])}")
            subprocess.run(cmd, cwd=DIFF_SOLVERS_DIR, check=True)

            fid = compute_fid(str(outdir), dataset_name, num_expected=fid_num,
                              device=torch.device("cuda"))
            print(f"[fid ] {dataset_name} {solver} NFE {nfe}: {fid:g}")
            write_header = not csv_path.exists()
            with open(csv_path, "a", newline="") as f:
                writer = csv.writer(f)
                if write_header:
                    writer.writerow(["dataset", "solver", "nfe", "fid", "fid_num"])
                writer.writerow([dataset_name, solver, nfe, f"{fid:.4f}", fid_num])
            if not keep_images:
                shutil.rmtree(outdir, ignore_errors=True)


if __name__ == "__main__":
    main()
